### mensaje de bienvenida
GET http://localhost:1234


### Recuperar toda la lista de investigadores
GET http://localhost:1234/investigadores

### Recuperar un investigador por su arquetipo
GET http://localhost:1234/investigadores?arquetipo=defensor

### Recuperar un investigador por la id
GET http://localhost:1234/investigadores/3

### Crear un nuevo investigador
POST http://localhost:1234/investigadores
Content-Type:application/json

{
  "nombrePJ": "Eugenia",
  "posicion": "Sanitaria",
  "ENposicion": "healthery",
  "vida": 7,
  "arquetipos":[
      "Defensor",
      "Explorador"
  ]
}

### Borrar un investigador
DELETE http://localhost:1234/investigadores/3

### Actualizar un investigador
PATCH http://localhost:1234/investigadores/2
Content-Type:application/json

{
  "vida": 8
}