### LISTAR TODOS LOS MAPAS DE UNA EXPANSION ---- BASE
GET http://localhost:1234/mapas?expansion=AHBase

### LISTAR TODOS LOS MAPAS DE UNA EXPANSION ---- MAREAS
GET http://localhost:1234/mapas?expansion=AHMareas

### LISTAR TODOS LOS MAPAS
GET http://localhost:1234/mapas

### PEDIR UN PAMA CONCRETO POR LA ID
GET http://localhost:1234/mapas/20


### CREAR UN NUEVO MAPA
POST http://localhost:1234/mapas
Content-Type: application/json

{
    "title": "primera prueba",
    "description": "En el corazón del infinito mora el aletargado Azathoth, arrullado por las incesantes notas de funestas flautas. Pero hay mortales que desean invocar el poder y la calamidad inconmensurables del Dios Ciego e Idiota, aunque ello suponga condenar a la humanidad ...",
    "expansion": "AHBase",
    "initialSpace": "Estación de trenes",
    "reservaDeMitos":{
        "perdicion": 3,
        "enemigos": 2,
        "pistas": 2,
        "periodico": 2,
        "explosion": 1,
        "retribucion": 1,
        "vacias": 3
    },
    "retribution": "Por cada Monstruo Sectario, coloca una ficha de Perdición en su espacio. (Si está en un espacio de calle, la ficha de perdición se coloca en un espacio de Barrio adyacente.)"
}

### BORRAR UN MAPA
DELETE http://localhost:1234/mapas/2527f629-3634-4411-a1bf-91fddcf69f8b

### EDITAR UN MAPA
PATCH http://localhost:1234/mapas/4
Content-Type: application/json

{
    "title": "prueba de edicion"
}