### Recuperar toda la lista de investigadores
GET http://localhost:1234/inv

### Recuperar lista de investigadores por su rol
GET http://localhost:1234/inv/previewList?rol=guardian

### Recuperar un investigador por la id
GET http://localhost:1234/inv/56

### Crear un nuevo investigador
POST http://localhost:1234/inv
Content-Type:application/json

{
  "nombrePJ": "Samuel Carrasco",
  "posicion": "Pintor",
  "ENposicion": "Painter",
  "vida": 9,
  "arquetipos":[
      "Defensor",
      "Explorador"
  ]
}

### Get numero de votos de un mapa likes - Dislikes
GET http://localhost:1234/inv/likeDislike/7

### llamada Like Dislike
POST http://localhost:1234/inv/likeDislike
Content-Type: application/json

{ 
    "idInv": 7,
    "idUser": "usert_2135",
    "value": 1
}

### Get lista de comentarios de un mapa
GET http://localhost:1234/inv/comments/7

### comentar en un mapa
POST http://localhost:1234/inv/comments
Content-Type: application/json

{ 
    "idInv": 7,
    "idUser": "user_135",
    "comment": "adoro este investigador por su versatilidad"
}

### Borrar un investigador
DELETE http://localhost:1234/inv/3e0e5792-2bea-4ec5-bee0-6d711fc683d0

### Actualizar un investigador
PATCH http://localhost:1234/inv/2
Content-Type:application/json

{
  "posicion": "el gran reportero de Arkham"
}

### Recuperar toda la lista de preview investigadores
GET http://localhost:1234/inv/previewList

### Get numero de votos de un mapa likes - Dislikes
GET http://localhost:1234/inv/likeDislike/30

### llamada Like Dislike
POST http://localhost:1234/inv/likeDislike
Content-Type: application/json

{ 
    "idInv": 7,
    "idUser": "user_2135",
    "value": -1
}
