### Recuperar toda la lista de investigadores
GET http://localhost:1234/inv

### Recuperar un investigador por su arquetipo
GET http://localhost:1234/inv?archetype=experto

### Recuperar un investigador por la id
GET http://localhost:1234/inv/56

### Crear un nuevo investigador
POST http://localhost:1234/inv
Content-Type:application/json

{
  "nombrePJ": "Samuel Carrasco",
  "posicion": "Pintor",
  "ENposicion": "Painter",
  "vida": 9,
  "arquetipos":[
      "Defensor",
      "Explorador"
  ]
}

### Borrar un investigador
DELETE http://localhost:1234/inv/3e0e5792-2bea-4ec5-bee0-6d711fc683d0

### Actualizar un investigador
PATCH http://localhost:1234/inv/2
Content-Type:application/json

{
  "posicion": "el gran reportero de Arkham"
}

### Obtener todos los objetos de un investigador
GET http://localhost:1234/inv/2/objects

### Obtener un objeto por us ID
GET http://localhost:1234/objects/2

### Recuperar toda la lista de preview investigadores
GET http://localhost:1234/inv/previewList

### Recuperar un investigador por su arquetipo
GET http://localhost:1234/inv/previewList?rol=rogue

### Get numero de votos de un mapa likes - Dislikes
GET http://localhost:1234/inv/likeDislike/30

### llamada Like Dislike
POST http://localhost:1234/inv/likeDislike
Content-Type: application/json

{ 
    "idInv": 7,
    "idUser": "user_2135",
    "value": -1
}

“‘No hay dos palabras en este mundo más dañinas que ‘buen trabajo’.’

Desde la primera vez que la escuché en Whiplash, esa frase se me grabó a fuego y me obsesionó. Dejando a un lado la obra maestra que es la película, el mensaje de pasión obsesiva que transmite funciona como un espejo para mí.

Me mata y me inspira a partes iguales: la odio por lo implacable que es… y la amo porque me empuja a no conformarme jamás, aunque a veces roce los límites de mi cordura.

En un mundo tan competitivo como el de hoy, donde la tecnología evoluciona cada día y lo “nuevo” caduca antes de asentarse, parece que no hay otra opción que la obsesión en busca del éxito.

Pero, ¿es bueno? ¿es malo? ¿es necesario? ¿es lo que realmente quiero?
Muchas noches me he quedado en vela por ser asi, porque por culpa de esto dejo de lado cosa que se que en un futuro daria lo que fuera por no haber sido asi, pero no veo otro camino.