### Recuperar toda la lista de mapas
GET http://localhost:1234/maps

### listar el preview de los mapas
GET http://localhost:1234/maps/previewMap

### Recuperar un mapa por su expansion
GET http://localhost:1234/maps?expansion=AHBase

### Recuperar un mapa por la id
GET http://localhost:1234/maps/0

### Obtener lista de votaciones
GET http://localhost:1234/maps/getAllVotesMaps

### Get numero de votos de un mapa likes - Dislikes
GET http://localhost:1234/maps/likeDislike/2

### llamada Like Dislike
POST http://localhost:1234/maps/likeDislike
Content-Type: application/json

{ 
    "idMap": 7,
    "idUser": "usert_2135",
    "value": 1
}

### Get tiempo estimado
GET http://localhost:1234/maps/timeEstimated/7

### POST tiempo estimado
POST http://localhost:1234/maps/timeEstimated
Content-Type: application/json

{ 
    "idMap": 7,
    "idUser": "user_1135",
    "value": 145
}

### Get dificultad de mapa
GET http://localhost:1234/maps/difficultyMap/7

### llamada votacion dificultad
POST http://localhost:1234/maps/difficultyMap
Content-Type: application/json

{ 
    "idMap": 7,
    "idUser": "user_135",
    "value": 3
}

### Get investigadores recomendados para un mapa
GET http://localhost:1234/maps/invRecommended/3

### Votar por investigador recomendado
POST http://localhost:1234/maps/invRecommended
Content-Type: application/json

{ 
    "idMap": 7,
    "idUser": "user_135",
    "idInv": 3,
    "comment": "este investigador es muy bueno para este mapa"
}

### Get lista de comentarios de un mapa
GET http://localhost:1234/maps/comments/7

### comentar en un mapa
POST http://localhost:1234/maps/comments
Content-Type: application/json

{ 
    "idMap": 7,
    "idUser": "user_135",
    "nameUser": "theGod",
    "comment": "heyyy esto es un comentario"
}

### Crear un nuevo mapa
POST http://localhost:1234/maps
Content-Type:application/json

{
    "title": "threre is no comming back",
    "description": "En el corazón del infinito mora el aletargado Azathoth, arrullado por las incesantes notas de funestas flautas. Pero hay mortales que desean invocar el poder y la calamidad inconmensurables del Dios Ciego e Idiota, aunque ello suponga condenar a la humanidad ...",
    "expansion": "AHBase",
    "initialSpace": "Estación de trenes",
    "reservaDeMitos":{
        "perdicion": 3,
        "enemigos": 2,
        "pistas": 2,
        "periodico": 2,
        "explosion": 1,
        "retribucion": 1,
        "vacias": 3
    },
    "retribution": "Por cada Monstruo Sectario, coloca una ficha de Perdición en su espacio. (Si está en un espacio de calle, la ficha de perdición se coloca en un espacio de Barrio adyacente.)"
}

### Borrar un mapa
DELETE http://localhost:1234/maps/b61d9da5-b740-4a45-9823-5d834440832e

### Actualizar un mapa
PATCH http://localhost:1234/maps/4574c2c6-e3e7-4a0c-8f12-17e1f8c1a24a
Content-Type:application/json

{
  "expansion": "AHNoche"
}

### Listar todos los enemigos
GET http://localhost:1234/enemies

### Listar todos los enemigos DE UN MAPA CONCRETO
GET http://localhost:1234/maps/enemies/5

### Listar todos los enemigos por expansion
GET http://localhost:1234/enemies?expansion=AHWaves

### Listar todos los enemigos tipo
GET http://localhost:1234/enemies?type=semilla estelar

### Buscar 1 enemigo concreto por la id
GET http://localhost:1234/enemies/2

