### Recuperar toda la lista de mapas en juego
GET http://localhost:1234/mapInPlay

### Recuperar un mapa en juego por la id
GET http://localhost:1234/mapInPlay/e4245d56-9bb8-4d26-8ff7-bd0502636aa7

### Recuperar los mapas de un usuario
GET http://localhost:1234/mapInPlay/users/user_2x7hdgi9dwczRgUdQy93PLpgrUq


### Pedir una ficha de mitos
GET http://localhost:1234/mapInPlay/5fd4dabb-3c6d-4b26-a399-40f71c23f4b9/getMithToken

### Reiniciar la reserva de mitos
GET http://localhost:1234/mapInPlay/0/ressetMithReserve


### Crear un nuevo mapa in Play
POST http://localhost:1234/mapInPlay
Content-Type:application/json

{
    "idMap": 1,
    "IDUserHost": "user_2x7hdgi9dwczRgUdQy93PLpgrUq"
}

### elimina un Mapa in play pasandole la id del mapa y la contraseña de berificación
POST http://localhost:1234/mapInPlay/deleteMapInPlay
Content-Type:application/json

{
    "id" : "2df273fc-5252-4303-aa39-1ba9331ffb42",
    "password": "666"
    
}

### Actualizar datos de un mapa in play
POST http://localhost:1234/mapInPlay/d6ef5fdd-672d-4c6e-84eb-f244031670ad/variable
Content-Type:application/json

{
  "key": "clues",
  "delta": -1
}

### añadir ficha a la reserva de mitos
POST http://localhost:1234/mapInPlay/0/token
Content-Type: application/json

{ 
    "action": "add",    
    "type": "retribution" 
}

### borrar ficha de la reserva de mitos
POST http://localhost:1234/mapInPlay/0/token
Content-Type: application/json

{ 
    "action": "remove",    
    "type": "retribution" 
}

### resetear una ficha de mitos ya revelada
POST http://localhost:1234/mapInPlay/0/token
Content-Type: application/json

{ 
    "action": "reset",    
    "type": "retribution" 
}