### CONTROL --- Obtener todos los datos referente a losetasOnLine
GET http://localhost:1234/losetasOnLine

### CONTROL --- Obtener todos los investigadores conectados
GET http://localhost:1234/losetasOnLine/allUsersOnLine

### CONTROL --- Obtener investigadores conectados de una zona
GET http://localhost:1234/losetasOnLine/zone/2

### Obtener 1 investigador random actualmente conectado de una zona concreta
GET http://localhost:1234/losetasOnLine/randomInvInZone/7

### POST de un investigador a una zona ---RECUERDA--- Antes de asignar una nueva zona, debes borrar la anterior
POST http://localhost:1234/losetasOnLine/newInvZone
Content-Type:application/json

{
  "idZone": "5",
  "idUser": "user12345",
  "invData": [{"name": "Investigador", "level": 1}],
  "available": true
}