// Emparejamiento Losetas

### CONTROL --- Obtener todos los datos referente a losetasOnLine
GET https://api-arkhamhorror-dev.up.railway.app/losetasOnLine

### CONTROL --- Obtener todos los investigadores conectados
GET https://api-arkhamhorror-dev.up.railway.app/losetasOnLine/allUsersOnLine

### CONTROL --- Obtener investigadores conectados de una zona
GET https://api-arkhamhorror-dev.up.railway.app/losetasOnLine/zone/2

### Obtener 1 investigador random actualmente conectado de una zona concreta
GET https://api-arkhamhorror-dev.up.railway.app/losetasOnLine/randomInvInZone/7/user_2x7hdgi9dwczRgUdQy93PpgrUq

### POST de un investigador a una zona ---RECUERDA--- Antes de asignar una nueva zona, debes borrar la anterior
POST https://api-arkhamhorror-dev.up.railway.app/losetasOnLine/newInvZone
Content-Type:application/json

{
  "idZone": 7,
  "idUser": "user12345",
  "invData": [{"name": "Investigador", "level": 1}],
  "available": true
}

// Interaccion entre jugadores - FASE 2 - Invitacion y creacion de evento

### CONTROL --- GET todas las interacciones (para admin/debug)
GET https://api-arkhamhorror-dev.up.railway.app/interactions

### GET General, para cuando llegue una invitacion al GEST
GET https://api-arkhamhorror-dev.up.railway.app/interactions/pending/user_2x7xEnynmyhmhzohJt9rDkXtEYuF

### GET Focus, de polling sobre novedad de interaccion
GET https://api-arkhamhorror-dev.up.railway.app/interactions/poll/203d2ef1-410e-4de7-91f3-8229ee6f6b43?idUser=user678

### NUEVO: PUT responder a invitación - ACEPTAR
PUT https://api-arkhamhorror-dev.up.railway.app/interactions/respond/29763963-7745-4234-99c2-51dec524f481
Content-Type:application/json

{
  "idUser": "user5678",
  "response": "accepted",
  "invData": [{"name": "Investigador Guest", "level": 2, "health": 100}]
}

### TODO hacer una llamada para cancelar encuentro por parte de alguno de los 2

### POST crear nueva interacción entre 2 usuarios
POST https://api-arkhamhorror-dev.up.railway.app/interactions
Content-Type:application/json

{
  "idUserHost": "user678",
  "idUserGuest": "user5678", 
  "invData": [{"name": "Super Investigador HOST", "level": 20, "health": 1000}],
  "type": "fight",
  "idLocationMap": 3
}
