### mensaje de bienvenida
GET https://api-arkhamhorror.up.railway.app

### Retorna el número de visitas totales a la app
GET https://api-arkhamhorror.up.railway.app/visitas

### Suma 1 al contador de visitas
POST https://api-arkhamhorror.up.railway.app/visitas
