### Recuperar toda la lista de mapaes
GET https://api-arkhamhorror.up.railway.app/maps

### Recuperar un mapa por su expansion
GET https://api-arkhamhorror.up.railway.app/maps?expansion=AHBase

### Recuperar un mapa por la id
GET https://api-arkhamhorror.up.railway.app/maps/1

### Crear un nuevo mapa
POST https://api-arkhamhorror.up.railway.app/maps
Content-Type:application/json

{
    "title": "primera prueba",

    "description": "En el corazón del infinito mora el aletargado Azathoth, arrullado por las incesantes notas de funestas flautas. Pero hay mortales que desean invocar el poder y la calamidad inconmensurables del Dios Ciego e Idiota, aunque ello suponga condenar a la humanidad ...",
    "expansion": "AHBase",
    "initialSpace": "Estación de trenes",
    "reservaDeMitos":{
        "perdicion": 3,
        "enemigos": 2,
        "pistas": 2,
        "periodico": 2,
        "explosion": 1,
        "retribucion": 1,
        "vacias": 3
    },
    "retribution": "Por cada Monstruo Sectario, coloca una ficha de Perdición en su espacio. (Si está en un espacio de calle, la ficha de perdición se coloca en un espacio de Barrio adyacente.)"
}

### Borrar un mapa
DELETE https://api-arkhamhorror.up.railway.app/maps/3e0e5792-2bea-4ec5-bee0-6d711fc683d0

### Actualizar un mapa
PATCH https://api-arkhamhorror.up.railway.app/maps/2
Content-Type:application/json

{
  "vida": 3
}